#!/usr/bin/env bash

set -euo pipefail

# This script is called by the elm-pair editor plugin first time it runs.
# The script downloads binaries for elm and elm-pair, replaces itself with the
# elm-pair binary downloaded, then starts that binary.

ELM_VERSION="0.19.1"
ELM_PAIR_VERSION="release-18"

function main {
  # Redirect stdout to stderr for the duration of this script. The editor plugin
  # calling this script expects only output from elm-pair itself on stdout.
  exec 3>&1
  exec 1>&2

  # Step into the directory containing this script.
  pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null

  # Download the right binaries for this platform.
  PLATFORM="$(uname -m)-$(uname)"
  case "$PLATFORM" in
    "x86_64-Darwin") download_binaries_for "mac-64-bit" "x86_64-darwin";;
    "arm64-Darwin") download_binaries_for "mac-64-bit" "x86_64-darwin";;
    "x86_64-Linux") download_binaries_for "linux-64-bit" "x86_64-linux";;
    *) no_binaries_for "$PLATFORM";;
  esac

  # Stop redirecting stdout to stderr and run elm-pair
  popd > /dev/null
  echo "Elm-pair installation complete!"
  exec 1>&3-
  exec "$0"
}

function download_binaries_for {
  ELM_DOWNLOAD="binary-for-$1.gz"
  ELM_PAIR_DOWNLOAD="elm-pair_$2.tar.gz"

  echo "Download Elm compiler $ELM_VERSION..."
  curl --remote-name --location \
    "https://github.com/elm/compiler/releases/download/$ELM_VERSION/$ELM_DOWNLOAD" \
    2> /dev/null
  gzip --decompress --stdout "$ELM_DOWNLOAD" > elm
  rm "$ELM_DOWNLOAD"
  chmod +x elm

  echo "Download Elm-pair $ELM_PAIR_VERSION..."
  curl --remote-name --location \
    "https://github.com/jwoudenberg/elm-pair/releases/download/$ELM_PAIR_VERSION/$ELM_PAIR_DOWNLOAD" \
    2> /dev/null
  tar --extract --gzip --to-stdout --file "$ELM_PAIR_DOWNLOAD" > elm-pair
  rm "$ELM_PAIR_DOWNLOAD"
  chmod +x elm-pair
}

function no_binaries_for {
  echo "No elm-pair binaries for platform $PLATFORM currently exist."
  echo ""
  echo "You can find the list of currently supported binaries here:"
  echo "https://github.com/jwoudenberg/elm-pair/releases"
  echo ""
  echo "To request a binary for your platform, please open an issue here:"
  echo "https://github.com/jwoudenberg/elm-pair/issues"
  exit 1
}

main
