name: Release
on:
  push:
    tags:
      - release-*
jobs:
  release-linux:
    name: release-linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - run: |
          cargo build \
            --target x86_64-unknown-linux-musl
            --manifest-path elm-pair/Cargo.toml \
            --release
          cd elm-pair/target/x86_64-unknown-linux-musl/release
          tar czf elm-pair_x86_64-linux.tar.gz elm-pair
      - uses: softprops/action-gh-release@v1
        with:
          body: For changes, see the [Changelog](https://github.com/jwoudenberg/elm-pair/tree/main/CHANGELOG.md).
          files: elm-pair/target/release/elm-pair_x86_64-linux.tar.gz
          token: ${{secrets.GITHUB_TOKEN}}

  release-macos:
    name: release-macos
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - run: |
          cargo build \
            --manifest-path elm-pair/Cargo.toml \
            --release
          cd elm-pair/target/release
          tar czf elm-pair_x86_64-darwin.tar.gz elm-pair
      - uses: softprops/action-gh-release@v1
        with:
          body: For changes, see the [Changelog](https://github.com/jwoudenberg/elm-pair/tree/main/CHANGELOG.md).
          files: elm-pair/target/release/elm-pair_x86_64-darwin.tar.gz
          token: ${{secrets.GITHUB_TOKEN}}
