name: Release
on:
  push:
    tags:
      - release-*
jobs:
  release:
    name: release
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - build: x86_64-linux
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
          - build: x86_64-darwin
            os: macos-11
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{matrix.target}}
          override: true
      - run: |
          cargo build --release --target ${{matrix.target}}
          tar czf \
            elm-pair_${{matrix.target}}.tar.gz \
            target/${{matrix.target}}/release/elm-pair
      - uses: softprops/action-gh-release@v1
        with:
          files: elm-pair_${{matrix.target}}.tar.gz
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
